version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rivy-postgres
    environment:
      POSTGRES_DB: rivy_storefront
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rivy-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: rivy-server
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: rivy_storefront
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: your-super-secret-jwt-key
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - rivy-network
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rivy-client
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - rivy-network
    command: npm start

volumes:
  postgres_data:

networks:
  rivy-network:
    driver: bridge
